### ISSUE TITLE
Not updating Database

### ISSUE THREAD

**Issue by SubwooferNL** [PokeSer/qb-tattooshop#3]
Heya nice script sofar,
the only issue is that it is not updating the tattoos on the players table..
he is removing money and placing tattoos but after a relog or something they are gone.
there are no errors

**Comment by ZZG994521** [comment]
But I don’t know why when I press esc, the screen gets stuck and I can’t click anything

**Comment by PokeSer** [comment]
now is updated to new [oxmysql](https://github.com/overextended/oxmysql) version.
