### ISSUE TITLE
There is no change after buying the tattoo, there is an error

### ISSUE THREAD

**Issue by ZZG994521** [PokeSer/qb-tattooshop#4]
[script:qb-tattooshop] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export execute in resource oxmysql
[script:qb-tattooshop] > TriggerCallback (@qb-core/server/functions.lua:78)
[script:qb-tattooshop] > handler (@qb-core/server/events.lua:119)

**Comment by PokeSer** [comment]
You need [oxmysql](https://github.com/overextended/oxmysql)
